version: "3"
services:
  react-app:
    image: react-app
    build: "./node-client"
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    build: "./server"
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/.env
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
